# Generated by Django 3.2 on 2022-05-09 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120)),
                ('calle_numero', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('ciudad', models.CharField(max_length=120)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=120, null=True)),
                ('pais', models.CharField(default='Mexico', max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
