# Generated by Django 3.2 on 2022-05-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talla',
            name='short',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
