# Generated by Django 3.2 on 2022-05-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallas', '0002_talla_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='talla',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
