# Generated by Django 3.2 on 2022-05-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
        ('skus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skumaster',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='skuproduct',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_skuproduct_set', to='marcas.marca'),
        ),
    ]
