# Generated by Django 3.2 on 2022-05-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0002_auto_20220503_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuproduct',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_skuproduct_set', to='skus.skumaster'),
        ),
    ]
