# Generated by Django 3.2 on 2022-05-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0003_alter_skuproduct_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skuproduct',
            options={'ordering': ['color', 'talla']},
        ),
    ]
