# Generated by Django 3.2 on 2022-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0004_alter_skuproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
