# Generated by Django 3.2 on 2022-05-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0006_auto_20220530_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skumaster',
            options={'ordering': ['sku']},
        ),
        migrations.AlterModelOptions(
            name='skuproduct',
            options={'ordering': ['master', 'color', 'talla']},
        ),
    ]
