# Generated by Django 3.2 on 2022-05-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('skus', '0008_auto_20220530_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='skumaster',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_skuproduct_set', to='categorias.categoria'),
        ),
        migrations.AddField(
            model_name='skumaster',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skumaster',
            name='meta_description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skumaster',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skumaster',
            name='secondary_keyword_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skumaster',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
