# Generated by Django 3.2 on 2022-08-30 22:14

from django.db import migrations
import imagekit.models.fields
import skus.models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0009_auto_20220531_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='skumaster',
            name='image_6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=skus.models.upload_location),
        ),
    ]
