# Generated by Django 3.2 on 2022-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
