# Generated by Django 3.2 on 2022-05-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220526_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_id']},
        ),
    ]
